
# rabbitmq 消费端配置
spring:
  rabbitmq:
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: manual
        # 限流
        prefetch: 1
    host: "47.92.249.250"
    port: 5672
    username: "admin"
    password: "123456"
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
    virtual-host: "/"
#    connection-timeout: 15000

  # redis 配置  // 先通过手动配置吧，之后实现自动注入
  redis:
#    clusters: 47.92.249.250:6379,47.92.249.250:6380    # Redis集群配置方式
    host: "47.92.249.250"
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 10000   # 这里有点糊糊的，不知道Duration配置，也不知道单位问题。但是加了这条，确实不会再等待一分钟
        min-idle: 2


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.renewable.centcontrol.pojo


spring.datasource:
  url: jdbc:mysql://47.92.249.250:3306/centcontrol?characterEncoding=utf-8
  username: renewable
  password: 123
  driver-class-name: com.mysql.jdbc.Driver


# logger
logging:
  file: logs/centcontrol.log
info:
  name: infoname

# server
server:
  port: 8040